<h1>
	Thanks for signing up with <?php echo $app ?>,
	<?php echo $user->username ?>
</h1>

<h2>
	This is an example email for resetting your passphrase, generated by views/Users/email/resend.php
</h2>

<p>
	You should make own view for resend emails, and then set the
	"Users"/"transactional"/"activation"/"subject" and
	"Users"/"transactional"/"activation"/"body" config fields.
</p>

<p>
	We should remember to put a link so you can set a password and activate your account,
	<?php echo Q_Html::a(
		'Users/activate?p=code='.urlencode($email->activationCode)
		 . '&e='.urlencode($email->address),
		'like this'
	) ?>
</p>

<p style="margin-top: 100px;">
	And somewhere on the bottom, you'll probably want to place a link to:
	<?php echo Q_Html::a(
		'Users/unsubscribe?code='.urlencode($email->authCode)
		 . '&e='.urlencode($email->address),
		'unsubscribe'
	) ?>
</p>
