/**
 * Autogenerated base class for the Places model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Places.js file.
 *
 * @module Places
 */
var Q = require('Q');
var Db = Q.require('Db');

/**
 * Base class for the Places model
 * @namespace Base
 * @class Places
 * @static
 */
module.exports = function () {
	
	/**
	 * The list of model classes
	 * @property tableClasses
	 * @type array
	 */
	this.tableClasses = [
		"Places_Nearby",
		"Places_Zipcode"
	];
	
	/**
	 * This method uses Db.connect() to establish a connection to database using information stored in the configuration.
	 * If the connection to Db object has already been made, it returns this Db object.
	 * @method db
	 * @return {Db} The database connection
	 */
	this.db = function () {
		return Db.connect('Places');
	};
	
	/**
	 * The connection name for the class
	 * @method connectionName
	 * @return {string} The name of the connection
	 */
	this.connectionName = function() {
		return 'Places';
	};

	/**
	 * Link to Places.Nearby model
	 * @property Nearby
	 * @type Places.Nearby
	 */
	this.Nearby = Q.require('Places/Nearby');
	/**
	 * Link to Places.Zipcode model
	 * @property Zipcode
	 * @type Places.Zipcode
	 */
	this.Zipcode = Q.require('Places/Zipcode');
	
	return this;
	
};