/**
 * Autogenerated base class for the Websites model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Websites.js file.
 *
 * @module Websites
 */
var Q = require('Q');
var Db = Q.require('Db');

/**
 * Base class for the Websites model
 * @namespace Base
 * @class Websites
 * @static
 */
module.exports = function () {
	
	/**
	 * The list of model classes
	 * @property tableClasses
	 * @type array
	 */
	this.tableClasses = [
		"Websites_Bio"
	];
	
	/**
	 * This method uses Db.connect() to establish a connection to database using information stored in the configuration.
	 * If the connection to Db object has already been made, it returns this Db object.
	 * @method db
	 * @return {Db} The database connection
	 */
	this.db = function () {
		return Db.connect('Websites');
	};
	
	/**
	 * The connection name for the class
	 * @method connectionName
	 * @return {string} The name of the connection
	 */
	this.connectionName = function() {
		return 'Websites';
	};

	/**
	 * Link to Websites.Bio model
	 * @property Bio
	 * @type Websites.Bio
	 */
	this.Bio = Q.require('Websites/Bio');
	
	return this;
	
};