<?php

/**
 * Autogenerated base class for the Websites model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Websites.php file.
 *
 * @module Websites
 */
/**
 * Base class for the Websites model
 * @class Base_Websites
 */
abstract class Base_Websites
{
	/**
	 * The list of model classes
	 * @property $table_classnames
	 * @type array
	 */
	static $table_classnames = array (
);

	/**
	 * This method uses Db::connect() to establish a connection to database using information stored in the configuration.
	 * If the connection to Db object has already been made, it returns this Db object.
	 * @method db
	 * @return {iDb} The database object
	 */
	static function db()
	{
		return Db::connect('Websites');
	}

	/**
	 * The connection name for the class
	 * @method connectionName
	 * @return {string} The name of the connection
	 */
	static function connectionName()
	{
		return 'Websites';
	}
};