/**
 * Autogenerated base class for the Awards model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Awards.js file.
 *
 * @module Awards
 */
var Q = require('Q');
var Db = Q.require('Db');

/**
 * Base class for the Awards model
 * @namespace Base
 * @class Awards
 * @static
 */
function Base () {
	return this;
}
 
module.exports = Base;

/**
 * The list of model classes
 * @property tableClasses
 * @type array
 */
Base.tableClasses = [
	"Awards_Charge",
	"Awards_Customer",
	"Awards_Subscription"
];

/**
 * This method calls Db.connect() using information stored in the configuration.
 * If this has already been called, then the same db object is returned.
 * @method db
 * @return {Db} The database connection
 */
Base.db = function () {
	return Db.connect('Awards');
};

/**
 * The connection name for the class
 * @method connectionName
 * @return {string} The name of the connection
 */
Base.connectionName = function() {
	return 'Awards';
};

/**
 * Link to Awards.Charge model
 * @property Charge
 * @type Awards.Charge
 */
Base.Charge = Q.require('Awards/Charge');

/**
 * Link to Awards.Customer model
 * @property Customer
 * @type Awards.Customer
 */
Base.Customer = Q.require('Awards/Customer');

/**
 * Link to Awards.Subscription model
 * @property Subscription
 * @type Awards.Subscription
 */
Base.Subscription = Q.require('Awards/Subscription');
