/**
 * Autogenerated base class for the Awards model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Awards.js file.
 *
 * @module Awards
 */
var Q = require('Q');
var Db = Q.require('Db');

/**
 * Base class for the Awards model
 * @namespace Base
 * @class Awards
 * @static
 */
module.exports = function () {
	
	/**
	 * The list of model classes
	 * @property tableClasses
	 * @type array
	 */
	this.tableClasses = [
		"Awards_Badge",
		"Awards_Earned",
		"Awards_Leader"
	];
	
	/**
	 * This method uses Db.connect() to establish a connection to database using information stored in the configuration.
	 * If the connection to Db object has already been made, it returns this Db object.
	 * @method db
	 * @return {Db} The database connection
	 */
	this.db = function () {
		return Db.connect('Awards');
	};
	
	/**
	 * The connection name for the class
	 * @method connectionName
	 * @return {string} The name of the connection
	 */
	this.connectionName = function() {
		return 'Awards';
	};

	/**
	 * Link to Awards.Badge model
	 * @property Badge
	 * @type Awards.Badge
	 */
	this.Badge = Q.require('Awards/Badge');
	/**
	 * Link to Awards.Earned model
	 * @property Earned
	 * @type Awards.Earned
	 */
	this.Earned = Q.require('Awards/Earned');
	/**
	 * Link to Awards.Leader model
	 * @property Leader
	 * @type Awards.Leader
	 */
	this.Leader = Q.require('Awards/Leader');
	
	return this;
	
};